logging:
    file: 
        name: logs/app.log
    level:
        root: ERROR
        "[org.springframework]": ERROR
        "[com.mak]": DEBUG

spring:
    main: 
        banner-mode: off
        lazy-initialization: true
